/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as DestinationsRouteImport } from './routes/destinations'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PackagesSlugRouteImport } from './routes/packages.$slug'
import { Route as GuideUberInSrinagarRouteImport } from './routes/guide.uber-in-srinagar'
import { Route as DestinationsSlugRouteImport } from './routes/destinations.$slug'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRoute = DestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesSlugRoute = PackagesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PackagesRoute,
} as any)
const GuideUberInSrinagarRoute = GuideUberInSrinagarRouteImport.update({
  id: '/uber-in-srinagar',
  path: '/uber-in-srinagar',
  getParentRoute: () => GuideRoute,
} as any)
const DestinationsSlugRoute = DestinationsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DestinationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/guide': typeof GuideRouteWithChildren
  '/packages': typeof PackagesRouteWithChildren
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/guide/uber-in-srinagar': typeof GuideUberInSrinagarRoute
  '/packages/$slug': typeof PackagesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/guide': typeof GuideRouteWithChildren
  '/packages': typeof PackagesRouteWithChildren
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/guide/uber-in-srinagar': typeof GuideUberInSrinagarRoute
  '/packages/$slug': typeof PackagesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/guide': typeof GuideRouteWithChildren
  '/packages': typeof PackagesRouteWithChildren
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/guide/uber-in-srinagar': typeof GuideUberInSrinagarRoute
  '/packages/$slug': typeof PackagesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/destinations'
    | '/guide'
    | '/packages'
    | '/services'
    | '/sitemap.xml'
    | '/team'
    | '/destinations/$slug'
    | '/guide/uber-in-srinagar'
    | '/packages/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/destinations'
    | '/guide'
    | '/packages'
    | '/services'
    | '/sitemap.xml'
    | '/team'
    | '/destinations/$slug'
    | '/guide/uber-in-srinagar'
    | '/packages/$slug'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/destinations'
    | '/guide'
    | '/packages'
    | '/services'
    | '/sitemap.xml'
    | '/team'
    | '/destinations/$slug'
    | '/guide/uber-in-srinagar'
    | '/packages/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  DestinationsRoute: typeof DestinationsRouteWithChildren
  GuideRoute: typeof GuideRouteWithChildren
  PackagesRoute: typeof PackagesRouteWithChildren
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TeamRoute: typeof TeamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations': {
      id: '/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/$slug': {
      id: '/packages/$slug'
      path: '/$slug'
      fullPath: '/packages/$slug'
      preLoaderRoute: typeof PackagesSlugRouteImport
      parentRoute: typeof PackagesRoute
    }
    '/guide/uber-in-srinagar': {
      id: '/guide/uber-in-srinagar'
      path: '/uber-in-srinagar'
      fullPath: '/guide/uber-in-srinagar'
      preLoaderRoute: typeof GuideUberInSrinagarRouteImport
      parentRoute: typeof GuideRoute
    }
    '/destinations/$slug': {
      id: '/destinations/$slug'
      path: '/$slug'
      fullPath: '/destinations/$slug'
      preLoaderRoute: typeof DestinationsSlugRouteImport
      parentRoute: typeof DestinationsRoute
    }
  }
}

interface DestinationsRouteChildren {
  DestinationsSlugRoute: typeof DestinationsSlugRoute
}

const DestinationsRouteChildren: DestinationsRouteChildren = {
  DestinationsSlugRoute: DestinationsSlugRoute,
}

const DestinationsRouteWithChildren = DestinationsRoute._addFileChildren(
  DestinationsRouteChildren,
)

interface GuideRouteChildren {
  GuideUberInSrinagarRoute: typeof GuideUberInSrinagarRoute
}

const GuideRouteChildren: GuideRouteChildren = {
  GuideUberInSrinagarRoute: GuideUberInSrinagarRoute,
}

const GuideRouteWithChildren = GuideRoute._addFileChildren(GuideRouteChildren)

interface PackagesRouteChildren {
  PackagesSlugRoute: typeof PackagesSlugRoute
}

const PackagesRouteChildren: PackagesRouteChildren = {
  PackagesSlugRoute: PackagesSlugRoute,
}

const PackagesRouteWithChildren = PackagesRoute._addFileChildren(
  PackagesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  DestinationsRoute: DestinationsRouteWithChildren,
  GuideRoute: GuideRouteWithChildren,
  PackagesRoute: PackagesRouteWithChildren,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TeamRoute: TeamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
